# BÀI TẬP VỀ NUMPY

Ma trận

In [2]:
import numpy as np

In [32]:
a = np.random.randint(0,10,(3,3)) 
b = np.random.randint(0,10,(3,3)) 
c = np.random.randint(0,10,(2,2))


In [10]:
def TongMatran(a,b):
    if a.shape != b.shape: # nếu 2 ma trận ko cùng kích thước
        return "Không cộng được"
    print (a + b)

TongMatran(a,b)

[[12 15  4]
 [ 6 14  5]
 [15  9 10]]


In [11]:
def HieuMatran(a,b):
    if a.shape != b.shape: # nếu 2 ma trận ko cùng kích thước
        return "Không trừ được"
    return (a - b)

HieuMatran(np.array(a),np.array(b))

array([[ 4, -1, -4],
       [-4,  0, -3],
       [ 1,  5,  4]])

In [5]:
def NhanMatran(a,b):
    if a.shape != b.shape: # nếu 2 ma trận ko cùng kích thước
        return "Không nhân được"
    return (a * b)

NhanMatran(np.array(a),np.array(b))

array([[28,  0, 30],
       [32, 18, 20],
       [ 1,  7, 21]])

In [6]:
def NhanMaTranVoiSoTuNhien(a,n):
    return a * n

print(a)
NhanMaTranVoiSoTuNhien(np.array(a),3)

[[4 0 6]
 [8 9 4]
 [1 7 7]]


array([[12,  0, 18],
       [24, 27, 12],
       [ 3, 21, 21]])

In [16]:
def ChiaMatran(a,b):
    if a.shape != b.shape: # nếu 2 ma trận ko cùng kích thước
        return "Không chia được"
    return (a / b)

ChiaMatran(np.array(a),np.array(b))

array([[2.        , 0.875     , 0.        ],
       [0.2       , 1.        , 0.25      ],
       [1.14285714, 3.5       , 2.33333333]])

In [9]:
def ChiaMaTranVoiSoTuNhien(a,n):
    return a / n

print(a)
ChiaMaTranVoiSoTuNhien(np.array(a),3)

[[4 0 6]
 [8 9 4]
 [1 7 7]]


array([[1.33333333, 0.        , 2.        ],
       [2.66666667, 3.        , 1.33333333],
       [0.33333333, 2.33333333, 2.33333333]])

In [11]:
def NoiMaTran(a,b):
    if a.shape[0] != b.shape[0]: # nếu 2 ma trận ko cùng số hàng
        return "Không nối được"
    return np.concatenate((a,b), axis=1) # Nối theo chiều ngang

print(a)
print(b)
NoiMaTran(np.array(a),np.array(b))

[[4 0 6]
 [8 9 4]
 [1 7 7]]
[[7 3 5]
 [4 2 5]
 [1 1 3]]


array([[4, 0, 6, 7, 3, 5],
       [8, 9, 4, 4, 2, 5],
       [1, 7, 7, 1, 1, 3]])

In [12]:
def NoiMaTran(a,b):
    if a.shape[0] != b.shape[0]: # nếu 2 ma trận ko cùng số hàng
        return "Không nối được"
    return np.concatenate((a,b), axis=0) # Nối theo chiều doc

print(a)
print(b)
NoiMaTran(np.array(a),np.array(b))

[[4 0 6]
 [8 9 4]
 [1 7 7]]
[[7 3 5]
 [4 2 5]
 [1 1 3]]


array([[4, 0, 6],
       [8, 9, 4],
       [1, 7, 7],
       [7, 3, 5],
       [4, 2, 5],
       [1, 1, 3]])

In [31]:
print(a)
print('\n')

print("in hàng 1 và 2 + in cột 1 và 2")
print(a[0:2,0:3]) # 0:2 là in hàng 1 và 2 + 0:3 là in cột 1 và 2
print('\n')

print("in tất cả các hàng + in cột 1 và 2")
print(a[:,0:2]) # : là in tất cả các hàng + 1:3 là in cột 1 và 2

[[4 0 6]
 [8 9 4]
 [1 7 7]]


in hàng 1 và 2 + in cột 1 và 2
[[4 0 6]
 [8 9 4]]


in tất cả các hàng + in cột 1 và 2
[[4 0]
 [8 9]
 [1 7]]


In [38]:
# tính định thức bậc 2 và bậc 3 

def DetBac2(c):
    return c[0,0]*c[1,1] - c[0,1]*c[1,0]
    
def DetBac2Ham(c):
    return np.linalg.det(c)

print(c)
print(DetBac2(np.array(c)))
print(DetBac2Ham(np.array(c)))

        

[[2 0]
 [0 7]]
14
13.999999999999996
